package com.seray.pork.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.seray.entity.OrderDetail;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ORDER_DETAIL".
*/
public class OrderDetailDao extends AbstractDao<OrderDetail, Long> {

    public static final String TABLENAME = "ORDER_DETAIL";

    /**
     * Properties of entity OrderDetail.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property OrderDetailId = new Property(1, String.class, "orderDetailId", false, "ORDER_DETAIL_ID");
        public final static Property ActualNumber = new Property(2, int.class, "actualNumber", false, "ACTUAL_NUMBER");
        public final static Property ActualWeight = new Property(3, float.class, "actualWeight", false, "ACTUAL_WEIGHT");
        public final static Property VehicleNumber = new Property(4, int.class, "vehicleNumber", false, "VEHICLE_NUMBER");
        public final static Property VehicleWeight = new Property(5, float.class, "vehicleWeight", false, "VEHICLE_WEIGHT");
        public final static Property State = new Property(6, int.class, "state", false, "STATE");
        public final static Property IsVehicle = new Property(7, String.class, "isVehicle", false, "IS_VEHICLE");
        public final static Property OrderNumber = new Property(8, String.class, "orderNumber", false, "ORDER_NUMBER");
        public final static Property ProductName = new Property(9, String.class, "productName", false, "PRODUCT_NAME");
        public final static Property AlibraryName = new Property(10, String.class, "alibraryName", false, "ALIBRARY_NAME");
        public final static Property Weight = new Property(11, float.class, "weight", false, "WEIGHT");
        public final static Property Number = new Property(12, int.class, "number", false, "NUMBER");
        public final static Property OrderDate = new Property(13, String.class, "orderDate", false, "ORDER_DATE");
        public final static Property BarCode = new Property(14, String.class, "barCode", false, "BAR_CODE");
        public final static Property Price = new Property(15, float.class, "price", false, "PRICE");
        public final static Property DiscountPrice = new Property(16, float.class, "discountPrice", false, "DISCOUNT_PRICE");
        public final static Property Amount = new Property(17, float.class, "amount", false, "AMOUNT");
        public final static Property Picture = new Property(18, String.class, "picture", false, "PICTURE");
    }


    public OrderDetailDao(DaoConfig config) {
        super(config);
    }
    
    public OrderDetailDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ORDER_DETAIL\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"ORDER_DETAIL_ID\" TEXT," + // 1: orderDetailId
                "\"ACTUAL_NUMBER\" INTEGER NOT NULL ," + // 2: actualNumber
                "\"ACTUAL_WEIGHT\" REAL NOT NULL ," + // 3: actualWeight
                "\"VEHICLE_NUMBER\" INTEGER NOT NULL ," + // 4: vehicleNumber
                "\"VEHICLE_WEIGHT\" REAL NOT NULL ," + // 5: vehicleWeight
                "\"STATE\" INTEGER NOT NULL ," + // 6: state
                "\"IS_VEHICLE\" TEXT," + // 7: isVehicle
                "\"ORDER_NUMBER\" TEXT," + // 8: orderNumber
                "\"PRODUCT_NAME\" TEXT," + // 9: productName
                "\"ALIBRARY_NAME\" TEXT," + // 10: alibraryName
                "\"WEIGHT\" REAL NOT NULL ," + // 11: weight
                "\"NUMBER\" INTEGER NOT NULL ," + // 12: number
                "\"ORDER_DATE\" TEXT," + // 13: orderDate
                "\"BAR_CODE\" TEXT," + // 14: barCode
                "\"PRICE\" REAL NOT NULL ," + // 15: price
                "\"DISCOUNT_PRICE\" REAL NOT NULL ," + // 16: discountPrice
                "\"AMOUNT\" REAL NOT NULL ," + // 17: amount
                "\"PICTURE\" TEXT);"); // 18: picture
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ORDER_DETAIL\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, OrderDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderDetailId = entity.getOrderDetailId();
        if (orderDetailId != null) {
            stmt.bindString(2, orderDetailId);
        }
        stmt.bindLong(3, entity.getActualNumber());
        stmt.bindDouble(4, entity.getActualWeight());
        stmt.bindLong(5, entity.getVehicleNumber());
        stmt.bindDouble(6, entity.getVehicleWeight());
        stmt.bindLong(7, entity.getState());
 
        String isVehicle = entity.getIsVehicle();
        if (isVehicle != null) {
            stmt.bindString(8, isVehicle);
        }
 
        String orderNumber = entity.getOrderNumber();
        if (orderNumber != null) {
            stmt.bindString(9, orderNumber);
        }
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(10, productName);
        }
 
        String alibraryName = entity.getAlibraryName();
        if (alibraryName != null) {
            stmt.bindString(11, alibraryName);
        }
        stmt.bindDouble(12, entity.getWeight());
        stmt.bindLong(13, entity.getNumber());
 
        String orderDate = entity.getOrderDate();
        if (orderDate != null) {
            stmt.bindString(14, orderDate);
        }
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(15, barCode);
        }
        stmt.bindDouble(16, entity.getPrice());
        stmt.bindDouble(17, entity.getDiscountPrice());
        stmt.bindDouble(18, entity.getAmount());
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(19, picture);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, OrderDetail entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String orderDetailId = entity.getOrderDetailId();
        if (orderDetailId != null) {
            stmt.bindString(2, orderDetailId);
        }
        stmt.bindLong(3, entity.getActualNumber());
        stmt.bindDouble(4, entity.getActualWeight());
        stmt.bindLong(5, entity.getVehicleNumber());
        stmt.bindDouble(6, entity.getVehicleWeight());
        stmt.bindLong(7, entity.getState());
 
        String isVehicle = entity.getIsVehicle();
        if (isVehicle != null) {
            stmt.bindString(8, isVehicle);
        }
 
        String orderNumber = entity.getOrderNumber();
        if (orderNumber != null) {
            stmt.bindString(9, orderNumber);
        }
 
        String productName = entity.getProductName();
        if (productName != null) {
            stmt.bindString(10, productName);
        }
 
        String alibraryName = entity.getAlibraryName();
        if (alibraryName != null) {
            stmt.bindString(11, alibraryName);
        }
        stmt.bindDouble(12, entity.getWeight());
        stmt.bindLong(13, entity.getNumber());
 
        String orderDate = entity.getOrderDate();
        if (orderDate != null) {
            stmt.bindString(14, orderDate);
        }
 
        String barCode = entity.getBarCode();
        if (barCode != null) {
            stmt.bindString(15, barCode);
        }
        stmt.bindDouble(16, entity.getPrice());
        stmt.bindDouble(17, entity.getDiscountPrice());
        stmt.bindDouble(18, entity.getAmount());
 
        String picture = entity.getPicture();
        if (picture != null) {
            stmt.bindString(19, picture);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public OrderDetail readEntity(Cursor cursor, int offset) {
        OrderDetail entity = new OrderDetail( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // orderDetailId
            cursor.getInt(offset + 2), // actualNumber
            cursor.getFloat(offset + 3), // actualWeight
            cursor.getInt(offset + 4), // vehicleNumber
            cursor.getFloat(offset + 5), // vehicleWeight
            cursor.getInt(offset + 6), // state
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // isVehicle
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // orderNumber
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // productName
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // alibraryName
            cursor.getFloat(offset + 11), // weight
            cursor.getInt(offset + 12), // number
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // orderDate
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // barCode
            cursor.getFloat(offset + 15), // price
            cursor.getFloat(offset + 16), // discountPrice
            cursor.getFloat(offset + 17), // amount
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18) // picture
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, OrderDetail entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setOrderDetailId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setActualNumber(cursor.getInt(offset + 2));
        entity.setActualWeight(cursor.getFloat(offset + 3));
        entity.setVehicleNumber(cursor.getInt(offset + 4));
        entity.setVehicleWeight(cursor.getFloat(offset + 5));
        entity.setState(cursor.getInt(offset + 6));
        entity.setIsVehicle(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setOrderNumber(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setProductName(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setAlibraryName(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setWeight(cursor.getFloat(offset + 11));
        entity.setNumber(cursor.getInt(offset + 12));
        entity.setOrderDate(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setBarCode(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setPrice(cursor.getFloat(offset + 15));
        entity.setDiscountPrice(cursor.getFloat(offset + 16));
        entity.setAmount(cursor.getFloat(offset + 17));
        entity.setPicture(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(OrderDetail entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(OrderDetail entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(OrderDetail entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
